apiVersion: v1
kind: ConfigMap
metadata:
  name: sailingapp-nginx
  namespace: sailingapp
data:
  allow-snippet-annotations: "false"
  sailingapp.conf: |

        upstream yas-server {
                server 127.0.0.1:8989;
        }

        server {
                listen 8080 default_server;
                listen [::]:8080 default_server;

                root /var/www/html;
                index index.html index.htm;
                server_name _;

                recursive_error_pages   on;
                proxy_intercept_errors  on;

                add_header Access-Control-Allow-Origin * always;

                # error 404 handler
                #
                error_page 404 /error404.html;
                location = /error404.html {
                        root /var/www/html;
                        internal;
                }

                location / {
                        try_files $uri $uri/ = 404;
                }

                # Actual api for watch face app
                #
                location /yas-api/ {

                        # preflight check of CORS. 
                        #
                        if ($request_method = 'OPTIONS') {
                                add_header 'Access-Control-Allow-Origin' '*';
                                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        
                                # Custom headers and headers various browsers *should* be OK with but aren't
                                #
                                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
 
                                # Tell client that this pre-flight info is valid for 20 days
                                #
                                add_header 'Access-Control-Max-Age' 1728000;
                                add_header 'Content-Length' 0;
                                return 204;
                        }

                        proxy_set_header        Host $host;
                        proxy_set_header        X-Real-IP $remote_addr;
                        proxy_pass              http://yas-server/;
                }                

                # handle favico
                #
                location /favicon.ico {
                        access_log      off;
                        log_not_found   off;
                        try_files $uri =204;
                }

        }