apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailingapp-processor
  labels:
    kubernetes.io/name: sailingapp-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      kubernetes.io/name: sailingapp-processor
  template:
    metadata:
      labels:
        kubernetes.io/name: sailingapp-processor
        kubernetes.io/language: go
    spec:
      containers:
        - name: sailingapp-processor
          image: ilaverlin/yas-processor:latest
          env:
            - name: YASR_logLevel
              value: "1" 
            - name: YASR_listener_port
              value: "8989"
            - name: YASR_otelEndpoint
              valueFrom:
                secretKeyRef:
                  name: sailingapp
                  key: OTEL_URL
            - name: YASR_kafka_broker
              valueFrom:
                secretKeyRef:
                  name: sailingapp
                  key: KAFKA_URL
            - name: YASR_kafka_topicName
              value: "yas-msgs"
            - name: YASR_pgUrl
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: wf_pg_url
