apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sailingapp

# setting labels
#
labels:
  - pairs:
      kubernetes.io/instance: sailingapp
      managed-by: kustomize

# setting annotations
#
commonAnnotations:
  version: "latest"

resources:
  - namespace.yaml
  - configmap-nginx.yaml  
  - deployment-api.yaml
  - deployment-bot.yaml
  - deployment-processor.yaml
  - service.yaml
  - ingress.yaml

