apiVersion: batch/v1
kind: Job
metadata:
  name: watchservice-restore
  namespace: watchface
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: watchservice-restore
          image: ilaverlin/pg-az-backup:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: watchface
                  key: PG_HOST
            - name: POSTGRES_DATABASE
              value: WatchService
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: watchface
                  key: az_storage_account
            - name: AZURE_SAS
              valueFrom:
                secretKeyRef:
                  name: watchface
                  key: az_sas_token
            - name: AZURE_CONTAINER_NAME
              value: pg-backup
            - name: RESTORE
              value: "yes"
            - name: DROP_PUBLIC
              value: "create" 

      restartPolicy: Never
  backoffLimit: 0