apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchface-dbsink
  labels:
    kubernetes.io/name: watchface-dbsink
spec:
  replicas: 1
  selector:
    matchLabels:
      kubernetes.io/name: watchface-dbsink
  template:
    metadata:
      labels:
        kubernetes.io/name: watchface-dbsink
    spec:
      containers:
        - name: watchface-dbsink
          image: ilaverlin/watchcluster-dbsink:latest
          env:
            - name: "DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE"
              value: "false"
            - name: Serilog__WriteTo__0__Args__uri
              valueFrom:
                secretKeyRef:
                  name: watchface
                  key: LOKI_URL
            - name: DbSinkConfiguration__OpenTelemetryCollectorUrl
              valueFrom:
                secretKeyRef:
                  name: watchface
                  key: OTEL_URL
            - name: KafkaConfiguration__BootstrapServers
              valueFrom:
                secretKeyRef:
                  name: watchface
                  key: KAFKA_URL
            - name: PgProviderConfiguration__server
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: host
            - name: PgProviderConfiguration__UserId
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: PgProviderConfiguration__Password
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 50Mi