apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: watchface

# setting labels
#
labels:
  - includeSelectors: true
    pairs:
      kubernetes.io/instance: watchface
      managed-by: kustomize

# setting annotations
#
commonAnnotations:
  version: "latest"

resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - configmap-homeroot.yaml  
  - deployment-api.yaml
  - deployment-dbsink.yaml
  - deployment-exchange.yaml
  - deployment-location.yaml
  - deployment-weather.yaml
  - service-wfapi.yaml
  - ingress.yaml
  - refresh-view.yaml
  - certificate.yaml