apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watchface
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Laverlin/WatchCluster'
    path: ""
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: watchface
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground