apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sailingapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Laverlin/WatchCluster'
    path: ""
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sailingapp
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground