apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# setting labels
#
labels:
  - includeSelectors: false
    pairs:
      managed-by: kustomize

resources:
  - namespace-sailingapp.yaml
  - namespace-watchface.yaml
  - postgres.yaml
  - argo-deploy-sailingapp.yaml
  - argo-deploy-watchface.yaml

secretGenerator:
  - name: sailingapp
    namespace: sailingapp
    envs:
      - ./base.env
  - name: watchface
    namespace: watchface
    envs:
      - ./base.env
  - name: pg-secret
    namespace: watchface
    envs:
      - ./pg-secret.env
  - name: pg-secret
    namespace: sailingapp
    envs:
      - ./pg-secret.env

generatorOptions:
  disableNameSuffixHash: true


