apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# setting labels
#
labels:
  - includeSelectors: false
    pairs:
      managed-by: kustomize

resources:
  - namespace-sailingapp.yaml
  - namespace-watchface.yaml
  - argo-deploy-sailingapp.yaml
  - argo-deploy-watchface.yaml

secretGenerator:
  - name: sailingapp
    namespace: sailingapp
    envs:
      - ./.env.secret
  - name: watchface
    namespace: watchface
    envs:
      - ./.env.secret

generatorOptions:
  disableNameSuffixHash: true


