{
 "title": "App Activity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Traefik",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum(process_start_time_seconds{namespace=\"traefik\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Success Responses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total {code!=\"200\", service=\"traefik-private\"}[$__range])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Requests/Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{ exported_service=\"watchface-watchface-api-40aa5d1055ecfa539cd5@kubernetescrd\" }[1m])*60) by (node)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg App Request Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(traefik_router_request_duration_seconds_sum{ exported_service=\"watchface-watchface-api-40aa5d1055ecfa539cd5@kubernetescrd\"}[5m]))\n/\nsum (rate(traefik_router_request_duration_seconds_count{ exported_service=\"watchface-watchface-api-40aa5d1055ecfa539cd5@kubernetescrd\"}[5m]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_api_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Requested",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_locationinfo_processed_counter_total{source_kind!=\"Empty\"}[$__range]))",
     "legendFormat": "Location"
    },
    {
     "expr": "sum(delta(wc_exchangerateinfo_processed_counter_total{source_kind!=\"Empty\"}[$__range]))",
     "legendFormat": "Exchange"
    },
    {
     "expr": "sum(delta(wc_weatherinfo_processed_counter_total{source_kind!=\"Empty\"}[$__range]))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wc_api_memoryitems_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Requests/Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "increase(wc_api_httprequest_count_total[5m])",
     "legendFormat": "req/min"
    }
   ]
  },
  {
   "title": "Avg Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance, job) (rate(wc_api_message_duration_sum[5m]))\n/\nsum by (instance, job) (rate(wc_api_message_duration_count[5m]) > 0)\n",
     "legendFormat": "duration"
    }
   ]
  },
  { "title": "Location Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Location Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_locationinfo_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(wc_locationinfo_processed_counter_total{status=\"Error\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_locationinfo_processed_counter_total[$__range])) by (source_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Items",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wc_locationinfo_memoryitems_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (rate(wc_locationinfo_processing_duration_sum[1m]))\n/\nsum (rate(wc_locationinfo_processing_duration_count[1m]) > 0)",
     "legendFormat": "duration"
    }
   ]
  },
  { "title": "Weather Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Weather Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_weatherinfo_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wc_weatherinfo_processed_counter_total{status=\"Error\"}[$__range])) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather Providers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_weatherinfo_processed_counter_total{source_kind=\"Remote\"} [$__range])) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance, job) (rate(wc_weatherinfo_processing_duration_sum[5m]))\n/\nsum by (instance, job) (rate(wc_weatherinfo_processing_duration_count[5m]) > 0)\n",
     "legendFormat": "duration"
    }
   ]
  },
  { "title": "Exchange Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Exchange Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_exchangerateinfo_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wc_exchangerateinfo_processed_counter_total{status=\"Error\"}[$__range])) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exchange Rate Providers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_exchangerateinfo_processed_counter_total{source_kind=\"Remote\", remote_source!=\"\"}[$__range])) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Request/Day ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wc_exchangerateinfo_processed_counter_total{source_kind=\"Remote\", remote_source!=\"\"} - wc_exchangerateinfo_processed_counter_total{source_kind=\"Remote\", remote_source!=\"\"} offset 24h ) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_exchangerateinfo_processed_counter_total[$__range])) by (source_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Items",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wc_exchangerateinfo_memoryitems_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(wc_exchangerateinfo_processing_duration_sum[1m]))/sum(rate(wc_exchangerateinfo_processing_duration_count[1m]) > 0)",
     "legendFormat": "duration"
    }
   ]
  },
  { "title": "Database Sync & YA Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "YA Bot Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_yasbot_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YA Requests/Day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_yasbot_message_counter_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YA Legacy API watch requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_api_httprequest_count_total{endpoint_name=\"RouteList\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YA API watch requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_restapi_request_duration_milliseconds_count{path=~\"/route-store/users/(.*)/routes\", query=~\".*limit.*\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Anlytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Uniq devices/month",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "SELECT * FROM uniq_month;" }
   ]
  },
  {
   "title": "Uniq devices/today",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH \n  \"New2\" as (SELECT C.\"RequestTime\"::date as \"time\", Count(distinct(D.\"id\")) as \"New\"\n    FROM \"DeviceInfo\" D inner join \"CityInfo\" C on D.\"id\" = C.\"DeviceInfoId\"\n    WHERE D.\"FirstRequestTime\"::date = C.\"RequestTime\"::date\n    GROUP BY C.\"RequestTime\"::date), \n\n  \"Old2\" as (SELECT C.\"RequestTime\"::date as \"time\", Count(distinct(D.\"id\")) as \"Old\"\n    FROM \"DeviceInfo\" D inner join \"CityInfo\" C on D.\"id\" = C.\"DeviceInfoId\"\n    WHERE D.\"FirstRequestTime\"::date != C.\"RequestTime\"::date \n    GROUP BY C.\"RequestTime\"::date)\n  \nSELECT \"New2\".time, \"New2\".\"New\", \"Old2\".\"Old\"  FROM \"New2\" JOIN \"Old2\" ON \"New2\".time = \"Old2\".time\nWHERE \"New2\".time::date = now()::date"
    }
   ]
  },
  {
   "title": "Uniq devices avg/h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', \"RequestTime\") as time,\n  count(distinct(\"DeviceInfoId\"))\nFROM\n  \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND date_trunc('hour', \"RequestTime\") != date_trunc('hour', now())\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Devices [range]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  COALESCE(D.\"DeviceName\", 'nil') as \"DeviceName\",\n  count(distinct(D.\"DeviceId\")) as \"Count\"\nFROM\n  \"DeviceInfo\" D JOIN \"CityInfo\" C ON D.\"id\" = C.\"DeviceInfoId\" AND $__timeFilter(C.\"RequestTime\")\n\nGROUP BY \n  D.\"DeviceName\"\nORDER BY \"Count\" desc"
    }
   ]
  },
  {
   "title": "Devices Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() as time, \"DeviceName\", \"count\" FROM total_devices\nORDER BY \"count\" desc;"
    }
   ]
  },
  {
   "title": "Versions [range]",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  COALESCE(\"FaceVersion\", 'nil') as \"Version\",\n  count(distinct(\"DeviceInfoId\")) as \"Count\"\nfrom \"CityInfo\" \n\nWHERE\n  $__timeFilter(\"RequestTime\")\ngroup by \"FaceVersion\"\norder by \"Count\" desc\n"
    }
   ]
  },
  {
   "title": "Versions Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT \"Version\", \"Count\" FROM total_versions\nORDER BY \"Count\" desc;\n"
    }
   ]
  },
  {
   "title": "Geo visual",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(\"DeviceInfoId\")) AS metric,\n  max(\"Lat\") AS lat, max(\"Lon\") lon, \"CityName\"\n\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND \"CityName\" is not NULL\nGROUP BY \"CityName\""
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"CityName\",\n  count(distinct(\"DeviceInfoId\")) AS \"Count\"\n\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND \"Lat\" IS NOT NULL\nGROUP BY \"CityName\"\nORDER BY \"Count\""
    }
   ]
  }
 ]
}