apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Setting the base resources
resources:
    - ../../base
    - scheduled-backup.yaml
# Override the secretGenerator from the base
secretGenerator:
    - name: watchface
      namespace: watchface
      envs:
        - ./hetzner.env
      behavior: merge
    - name: sailingapp
      namespace: sailingapp
      envs:
        - ./hetzner.env
      behavior: merge
generatorOptions:
    disableNameSuffixHash: true
patches:
    - target:
        group: argoproj.io
        version: v1alpha1
        kind: Application
        name: watchface
      patch: |-
        [
          {
            "op": "replace",
            "path": "/spec/source/path",
            "value": "deploy/argo-watchface/overlays/hetzner"
          }
        ]
    - target:
        group: argoproj.io
        version: v1alpha1
        kind: Application
        name: sailingapp
      patch: |-
        [
          {
            "op": "replace",
            "path": "/spec/source/path",
            "value": "deploy/argo-sailingapp/overlays/hetzner"
          }
        ]
    - target:
        group: "postgresql.cnpg.io"
        version: "v1"
        kind: "Cluster"
        name: "pg-watchface"
      patch: |-
        [
          {
            "op": "replace",
            "path": "/spec/backup/barmanObjectStore/destinationPath",
            "value": "s3://ib.pg-backup/pg-hetzner"
          },
          {
            "op": "replace",
            "path": "/spec/externalClusters/0/barmanObjectStore/destinationPath",
            "value": "s3://ib.pg-backup/pg-hetzner-backup"
          }
        ]        