apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization



# Setting the base resources
resources:
  - ../../base

# Patches
patches:
  - target:
      kind: "Deployment"
      labelSelector: "kubernetes.io/language=go"
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/1/env/0/value",
          "value": "1"
        }
      ]
  - target:
      group: "traefik.io"
      version: "v1alpha1"
      kind: "IngressRoute"
      name: "sailingapp"
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/routes/0/match",
          "value": "Host(`watch.bdgn.me`) && PathPrefix(`/yas-api/`)"
        }
      ]

# Optional: you can modify replicas for dev environment
replicas:
  - name: sailingapp-api
    count: 1

# Optional: override common annotations for the dev environment
commonAnnotations:
  environment: "dev"
  version: "latest"
