apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sailingapp

# setting labels
#
commonLabels:
  kubernetes.io/instance: sailingapp
  managed-by: kustomize

# setting annotations
#
commonAnnotations:
  version: "latest"

secretGenerator:
  - name: sailingapp
    envs:
      - ./.env.secret

# generatorOptions:
#   disableNameSuffixHash: true

resources:
  - namespace.yaml
  - configmap-nginx.yaml  
  - deployment-api.yaml
  - deployment-bot.yaml
  - deployment-processor.yaml
  - service.yaml
  - ingress.yaml

