name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYDDD

    - name: Write version
      shell: pwsh
      run: |
        Write-Host "version=1.0.${{steps.current-time.outputs.formattedTime}}.${{github.run_number}}" >> $GITHUB_ENV
        $projFiles = Get-Childitem -Include *Service.csproj, *Abstract.csproj -Recurse
        foreach($projFile in $projFiles)
        {
          Write-Host "Writing version ${{ env.version }} in $projFile"
          [xml]$projXml = Get-Content -Path $projFile
          $projXml.Project.PropertyGroup.AssemblyVersion = ${{ env.version }}
          $projXml.Project.PropertyGroup.Version = "${{ env.version }}-stable"
          $projXml.Save($projFile)
        }

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
