name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYDDD

    - name: Set environment
      run: |
        echo "version=1.0.${{steps.current-time.outputs.formattedTime}}.${{github.run_number}}" >> $GITHUB_ENV


    - name: Write version
      shell: pwsh
      run: |
        $projFiles = Get-Childitem -Include *ServiceHost.csproj, *Abstract.csproj, *Api.csproj -Recurse
        $version = "${{ env.version }}"
        foreach($projFile in $projFiles)
        {
          Write-Host "Writing version $version in $projFile"
          [xml]$projXml = Get-Content -Path $projFile
          $projXml.Project.PropertyGroup.AssemblyVersion = $version
          $projXml.Project.PropertyGroup.Version = "$version-stable"
          $projXml.Save($projFile)
          Write-Host "new value $($projXml.Project.PropertyGroup.Version)"
        }

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push API
      uses: docker/build-push-action@v2
      with:
        file: ./IB.WatchCluster.Api/Dockerfile
        push: true
        tags: ilaverlin/watchcluster-api:latest   
        
    - name: Build and push ServiceHost
      uses: docker/build-push-action@v2
      with:
        file: ./IB.WatchCluster.ServiceHost/Dockerfile
        push: true
        tags: ilaverlin/watchcluster-servicehost:latest           
      
